name: dev-pipeline-ci

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
      - name: Build with Gradle+
        run: ./gradlew build

      - name: Run Kover
        run: ./gradlew koverHtmlReportDebug
      - name: Run Kover
        run: ./gradlew koverXmlReportDebug
      - name: Upload Coverage to CodeCov
        uses: codecov/codecov-action@v4
        with:
          files: ./build/reports/kover/reportDebug.xml
          fail_ci_if_error: true